### ISSUE TITLE
Standards 

### ISSUE THREAD

**Issue by ubogdan** [swaggo/fasthttp-swagger#1]
It would be nice if this package would import [file](https://github.com/swaggo/files) instead of having its own embedded package.

The most important reason is maintenance. It will be a pain to update the UI version.

**Comment by sdghchj** [comment]
What's the difference between v1 and v2 of https://github.com/swaggo/files?
Tag v1.0.2 has imported [file](https://github.com/swaggo/files) v2.0.1 to fix this issue.

**Comment by ubogdan** [comment]
v1 uses "golang.org/x/net/webdav" to embed the files and it require github.com/UnnoTed/fileb0x to embed them
v2 uses standard "embed" package 

another thing is that v2 have never SWAG UI version then v1.

Since swag is supporting versions > 1.18 
I think you are safe to start using v2.

**Comment by sdghchj** [comment]
OK
